name: Run command

on:
  # Manual trigger in the Actions tab
  workflow_dispatch:
    inputs:
      COMMAND:
        description: "command to run"
        required: true

jobs:
  fetch_and_unzip:
    runs-on: ubuntu-latest

    steps:
      # 1. Get current repo contents
      - name: Check out repo
        uses: actions/checkout@v4
      # 3. Unzip every *.zip in the repo (including the one we just downloaded)
      - name: Run command
        run: |
          ${{ github.event.inputs.COMMAND }}

      # 5. Commit & push only if new or changed files exist
      - name: Commit and push changes
        env:
          GH_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GH_NAME:  github-actions[bot]
        run: |
          git config user.email "$GH_EMAIL"
          git config user.name  "$GH_NAME"
          git add -A
          if git diff --cached --quiet; then
            echo "Nothing new to commit."
          else
            git commit -m "CI: extract zip archives"
            git push
          fi
